/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Serdin
 */
public class AdaugaClient extends javax.swing.JFrame {

    /**
     * Creates new form AdaugaClient3
     */
    public AdaugaClient() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        AgentComboBox.removeAllItems();
        AgentComboBox.addItem(login.Login.User);
        AgentComboBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        ObservatiiClientTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AgentComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NumeClientTextField = new javax.swing.JTextField();
        TelefonClientTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PrenumeClientTextField = new javax.swing.JTextField();
        EmailClientTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SalveazaButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        InserareMeniu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ObservatiiClientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObservatiiClientTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Adauga Client");

        jLabel7.setText("Agent");

        jLabel2.setText("Nume");

        AgentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Telefon");

        TelefonClientTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonClientTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Prenume");

        jLabel5.setText("E-mail");

        jLabel6.setText("Observatii");

        SalveazaButton.setText("Salveaza");
        SalveazaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalveazaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumeClientTextField)
                            .addComponent(TelefonClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrenumeClientTextField)
                            .addComponent(EmailClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(108, 108, 108)
                        .addComponent(ObservatiiClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(AgentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(449, 449, 449)
                        .addComponent(SalveazaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(1034, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NumeClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(PrenumeClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TelefonClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(EmailClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ObservatiiClientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AgentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalveazaButton))
                .addContainerGap(797, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(106, 26));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(112, 56));

        jMenu1.setText("Cauta Oferta/Cerere");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Oferta Vanzare Apartament");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Oferta Inchiriere Apartament");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Cerere Inchiriere Apartament");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Cerere Cumparare Apartament");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        InserareMeniu.setBackground(new java.awt.Color(153, 153, 153));
        InserareMeniu.setText("Inserare");
        InserareMeniu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InserareMeniu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                InserareMeniuMenuSelected(evt);
            }
        });
        InserareMeniu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserareMeniuMouseClicked(evt);
            }
        });
        InserareMeniu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserareMeniuActionPerformed(evt);
            }
        });
        jMenuBar1.add(InserareMeniu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelefonClientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonClientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonClientTextFieldActionPerformed

    private void ObservatiiClientTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObservatiiClientTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObservatiiClientTextFieldActionPerformed

    private void SalveazaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalveazaButtonActionPerformed
              this.jLabel2.setForeground(null);
              this.jLabel3.setForeground(null);
              this.jLabel4.setForeground(null);
              PreparedStatement myStmt = null;
               boolean flagNull=false;
               boolean flagSalvare=false;
               boolean flagInt=false;
               
                try {
        //DriverManager.registerDriver(new com.mysql.jdbc.Driver());
        if(NumeClientTextField.getText().isEmpty()){
            flagNull=true;
            this.jLabel2.setForeground(Color.red);
            
        }
        
        if(PrenumeClientTextField.getText().isEmpty()){
            flagNull=true;
            this.jLabel4.setForeground(Color.red);
        }
        

        try{
            Integer.parseInt(TelefonClientTextField.getText());
        }
        catch(NumberFormatException e){
            flagInt=true;
        }
        if(flagInt==true){
            this.jLabel3.setForeground(Color.red);
            JOptionPane.showMessageDialog(AdaugaClient.this,"Va rugam sa introduceti un numar de telefon valid","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        if((flagNull==false)&&(flagInt==false)){
        Class.forName("com.mysql.jdbc.Driver");

       Connection conn = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/imobiliare", "razvan", "razvan");
        
        

        myStmt = conn.prepareStatement("insert into clienti"
					+ " (Nume, Prenume, Telefon,Email,AgentID,NumeAgent,Observatii)"
					+ " values (?, ?, ?, ?,?,?,?)");
			
			// set params
			myStmt.setString(1, NumeClientTextField.getText());
			myStmt.setString(2, PrenumeClientTextField.getText());
                        
                       
			myStmt.setInt(3, Integer.parseInt(TelefonClientTextField.getText()));
			myStmt.setString(4, EmailClientTextField.getText());
                        myStmt.setString(7, ObservatiiClientTextField.getText());
                       
			myStmt.setInt(5, login.Login.UserId);
                        myStmt.setString(6, login.Login.User);
			myStmt.executeUpdate();
                        
                        flagSalvare=true;
                        System.out.println("in curs de salvare");
                        conn.close();
                        
                }
         if((flagNull==true)&&(flagInt==false)){
            JOptionPane.showMessageDialog(AdaugaClient.this,"Va rugam sa completati toate campurile marcate cu rosu","Error Message",JOptionPane.ERROR_MESSAGE);
        }
         
                }
                catch(Exception e){
                    e.printStackTrace();
                    System.out.println("in curs de salvare 2");
                }
                if(flagSalvare==true){
                    System.out.println("s-a salvat");
                    JOptionPane.showMessageDialog(AdaugaClient.this,"Client Salvat","",JOptionPane.INFORMATION_MESSAGE);
                        this.setVisible(false);
                        MeniuInserare m=new MeniuInserare();
                        m.setVisible(true);
                }
                

    }//GEN-LAST:event_SalveazaButtonActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CautaOVA s=new CautaOVA();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CautaOIA s=new CautaOIA();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CautaCIA s=new CautaCIA();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        CautaCCA s=new CautaCCA();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void InserareMeniuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_InserareMeniuMenuSelected
        MeniuInserare dialog = new MeniuInserare();
        this.setVisible(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_InserareMeniuMenuSelected

    private void InserareMeniuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserareMeniuMouseClicked

    }//GEN-LAST:event_InserareMeniuMouseClicked

    private void InserareMeniuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserareMeniuActionPerformed
        MeniuInserare dialog = new MeniuInserare();

        // show dialog
        //m.setVisible(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_InserareMeniuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaugaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaugaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaugaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaugaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdaugaClient().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AgentComboBox;
    private javax.swing.JTextField EmailClientTextField;
    private javax.swing.JMenu InserareMeniu;
    private javax.swing.JTextField NumeClientTextField;
    private javax.swing.JTextField ObservatiiClientTextField;
    private javax.swing.JTextField PrenumeClientTextField;
    private javax.swing.JButton SalveazaButton;
    private javax.swing.JTextField TelefonClientTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
