/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vladutz
 */
public class Apt_Vanzare_meniu extends javax.swing.JFrame {

    /**
     * Creates new form Apt_Vanzare_meniu
     */
    public Apt_Vanzare_meniu() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        
         ImageIcon aboutIcon = new ImageIcon("poza1.jpg");
        ImageIcon addIcon = new ImageIcon("poza1.jpg");
        ImageIcon copyIcon = new ImageIcon("poza1.jpg");

        Object[][] data =
        {
            {aboutIcon, "x","1","oca111","poza","regie","regie","Splaiul","30","da","3","parter","123234","12.21.12","nebuniii"},
            {addIcon, "Add","dada"},
            {copyIcon, "Copy","dada"},
            {copyIcon, "Copy","sadad"},
        };
        
        String[] columnNames = {"Exp", "Nr","Cod","Poza","Zona","Reper","Strada","Cam","Tip","ST","Etaj","Pret","Data","Actiuni"};
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        jTable1.setModel(model);
        jTable1.setVisible(false);
        
      
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Pozitie1 = new javax.swing.JCheckBox();
        Pozitie2 = new javax.swing.JCheckBox();
        Pozitie3 = new javax.swing.JCheckBox();
        Pozitie4 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        Dest1 = new javax.swing.JCheckBox();
        Dest2 = new javax.swing.JCheckBox();
        Dest3 = new javax.swing.JCheckBox();
        Dest4 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        Camera1 = new javax.swing.JCheckBox();
        Camera2 = new javax.swing.JCheckBox();
        Camera3 = new javax.swing.JCheckBox();
        Camera4 = new javax.swing.JCheckBox();
        Camera5 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        Metrou = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        Confort1 = new javax.swing.JCheckBox();
        Confort2 = new javax.swing.JCheckBox();
        Confort3 = new javax.swing.JCheckBox();
        Confort4 = new javax.swing.JCheckBox();
        Confort5 = new javax.swing.JCheckBox();
        Confort6 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        Mobila1 = new javax.swing.JCheckBox();
        Mobila2 = new javax.swing.JCheckBox();
        Mobila3 = new javax.swing.JCheckBox();
        Mobila4 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        Bucatarie1 = new javax.swing.JCheckBox();
        Bucatarie2 = new javax.swing.JCheckBox();
        Bucatarie3 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        EUR = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        Exclusivitate = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        Tip1 = new javax.swing.JCheckBox();
        Tip2 = new javax.swing.JCheckBox();
        Tip3 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        Clientifavoriti = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        Cuimagini = new javax.swing.JCheckBox();
        Faraimagini = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        Publicate = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        Stare1 = new javax.swing.JCheckBox();
        Stare2 = new javax.swing.JCheckBox();
        Stare3 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cautare...");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Dupa COD: ");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Selecteaza");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Dupa Strada:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton2.setText("Selecteaza");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("de la:");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("la:");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Selecteaza");

        jLabel6.setBackground(new java.awt.Color(255, 255, 102));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("   Zona:");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(255, 255, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("  Pozitie:");
        jLabel7.setOpaque(true);

        Pozitie1.setText("Ultracentral");
        Pozitie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pozitie1ActionPerformed(evt);
            }
        });

        Pozitie2.setText("Central");

        Pozitie3.setText("Cartier");

        Pozitie4.setText("Periferie");

        jLabel8.setBackground(new java.awt.Color(255, 255, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Destinatie:");
        jLabel8.setOpaque(true);

        Dest1.setText("Rezidential");

        Dest2.setText("Comercial");

        Dest3.setText("Birouri");

        Dest4.setText("Vacanta");

        jLabel9.setBackground(new java.awt.Color(255, 255, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Camere:");
        jLabel9.setOpaque(true);

        Camera1.setText("Garsoniera");

        Camera2.setText("2 camere");

        Camera3.setText("3 camere");

        Camera4.setText("3 camere");

        Camera5.setText("4+ camere");

        jLabel10.setBackground(new java.awt.Color(255, 255, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Metrou:");
        jLabel10.setOpaque(true);

        Metrou.setText("Metrou");

        jLabel11.setBackground(new java.awt.Color(255, 255, 102));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("  Confort:");
        jLabel11.setOpaque(true);

        Confort1.setText("I+");
        Confort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confort1ActionPerformed(evt);
            }
        });

        Confort2.setText("I");

        Confort3.setText("II+");

        Confort4.setText("II");

        Confort5.setText("III+");

        Confort6.setText("III");

        jLabel12.setBackground(new java.awt.Color(255, 255, 102));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("      Mobila:");
        jLabel12.setOpaque(true);

        Mobila1.setText("Nemobilat");

        Mobila2.setText("Mobilat partial");

        Mobila3.setText("Mobilat complet");
        Mobila3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mobila3ActionPerformed(evt);
            }
        });

        Mobila4.setText("Mobilat lux");

        jLabel13.setBackground(new java.awt.Color(255, 255, 102));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("      Bucatarie:");
        jLabel13.setOpaque(true);

        Bucatarie1.setText("Nemobilata");
        Bucatarie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bucatarie1ActionPerformed(evt);
            }
        });

        Bucatarie2.setText("Mobilata partial");

        Bucatarie3.setText("Mobilata complet");
        Bucatarie3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bucatarie3ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 102));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("        Imbunatatiri reale:");
        jLabel14.setOpaque(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 102));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("         Pret :");
        jLabel15.setOpaque(true);

        jLabel16.setText("mai mic de:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        EUR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setBackground(new java.awt.Color(255, 255, 102));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("         Etaj:");
        jLabel17.setOpaque(true);

        jLabel18.setText("intre:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel19.setText("si");

        jCheckBox28.setText("Fara Parter");

        jCheckBox29.setText("Fara Ultimul Etaj");

        jLabel20.setBackground(new java.awt.Color(255, 255, 102));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("        Exclusivitate:");
        jLabel20.setOpaque(true);

        Exclusivitate.setText("Exclusivitate");
        Exclusivitate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExclusivitateActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 102));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("              Tip:");
        jLabel21.setOpaque(true);

        Tip1.setText("Semidecomandat");

        Tip2.setText("Decomandat");

        Tip3.setText("Circular");

        jLabel22.setBackground(new java.awt.Color(255, 255, 102));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("           Agent:");
        jLabel22.setOpaque(true);

        jRadioButton1.setText("Echipa");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButton2.setText("Agent");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Clientifavoriti.setText("Clienti favoriti");

        jLabel23.setBackground(new java.awt.Color(255, 255, 102));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("         An Constructie:");
        jLabel23.setOpaque(true);

        jLabel24.setText("An:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setBackground(new java.awt.Color(255, 255, 102));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("         Imagini:");
        jLabel25.setOpaque(true);

        Cuimagini.setText("Cu Imagini");
        Cuimagini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuimaginiActionPerformed(evt);
            }
        });

        Faraimagini.setText("Fara Imagini");

        jLabel26.setBackground(new java.awt.Color(255, 255, 102));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("         Publicate:");
        jLabel26.setOpaque(true);

        Publicate.setText("Publicate");

        jLabel27.setBackground(new java.awt.Color(255, 255, 102));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("         Web:");
        jLabel27.setOpaque(true);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(255, 255, 102));
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("             Stare:");
        jLabel28.setOpaque(true);

        Stare1.setText("Actual");

        Stare2.setText("Incorect");

        Stare3.setText("Vandut");

        jLabel29.setBackground(new java.awt.Color(255, 255, 102));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("            Status:");
        jLabel29.setOpaque(true);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setText("Cauta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Reset");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dest4)
                                    .addComponent(Dest3)
                                    .addComponent(Dest2)
                                    .addComponent(Dest1)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pozitie4)
                                    .addComponent(Pozitie3)
                                    .addComponent(Pozitie2)
                                    .addComponent(Pozitie1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(197, 197, 197))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Camera5)
                                    .addGap(566, 566, 566))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Camera4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Camera3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(534, 534, 534))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(Camera2)
                                            .addGap(483, 483, 483))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                        .addComponent(Camera1)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(50, 50, 50)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addGap(10, 10, 10)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(Confort3)
                                                                                .addComponent(Confort4)
                                                                                .addComponent(Confort5)
                                                                                .addComponent(Confort6))
                                                                            .addGap(120, 120, 120)
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(Mobila3)
                                                                                .addComponent(Mobila4)
                                                                                .addComponent(Mobila2)
                                                                                .addComponent(Mobila1)))
                                                                        .addComponent(Confort1)
                                                                        .addComponent(Confort2))
                                                                    .addGap(46, 46, 46))
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(100, 100, 100)
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(225, 225, 225)
                                                            .addComponent(Bucatarie1))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(225, 225, 225)
                                                            .addComponent(Bucatarie2))))
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Metrou)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Bucatarie3)
                                                    .addGap(40, 40, 40))
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(59, 59, 59))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox28)
                            .addComponent(jCheckBox29)
                            .addComponent(Exclusivitate)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(212, 212, 212)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jRadioButton1)
                                        .addComponent(Tip1)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tip2)
                                        .addComponent(Tip3)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioButton2)
                                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Clientifavoriti))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cuimagini)
                                    .addComponent(Faraimagini)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Publicate)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Stare1)
                                        .addComponent(Stare2)
                                        .addComponent(Stare3)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1710, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel28))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Confort1)
                                        .addComponent(Mobila1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Camera1)
                                        .addComponent(jLabel16)
                                        .addComponent(Tip1)
                                        .addComponent(jLabel24)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Stare1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cuimagini)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Faraimagini)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Publicate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Stare2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Stare3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton4)
                                            .addComponent(jButton5)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pozitie1)
                                    .addComponent(Camera2)
                                    .addComponent(Confort2)
                                    .addComponent(Mobila2)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tip2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pozitie2)
                                            .addComponent(Camera3)
                                            .addComponent(Confort3)
                                            .addComponent(Mobila3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pozitie3)
                                            .addComponent(Camera4)
                                            .addComponent(Confort4)
                                            .addComponent(Mobila4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pozitie4)
                                            .addComponent(Camera5)
                                            .addComponent(Confort5)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Confort6)
                                            .addComponent(Bucatarie1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(Bucatarie2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Dest1)
                                            .addComponent(Metrou)
                                            .addComponent(Bucatarie3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Dest2)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Dest3)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dest4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Tip3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Clientifavoriti))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exclusivitate)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Boolean bolpoz=false;
        String String1=null;
        if(bolpoz==false){
        if(Pozitie1.isSelected()){
             bolpoz=true;
             String1=" AND Pozitie=Ultracentral";
        }
        }
        else{
          if(Pozitie1.isSelected()){
             bolpoz=true;
             String1=" OR Pozitie=Ultracentral";
        }
        }
        if(bolpoz==false){
        if(Pozitie2.isSelected()){
             bolpoz=true;
             String1=" AND Pozitie=Central";
        }
        }
        else{
          if(Pozitie2.isSelected()){
             bolpoz=true;
             String1=" OR Pozitie=Central";
        }  
        }
         if(bolpoz==false){
        if(Pozitie3.isSelected()){
             bolpoz=true;
             String1=" AND Pozitie=Cartier";
        }
        }
        else{
          if(Pozitie3.isSelected()){
             bolpoz=true;
             String1=" OR Pozitie=Cartier";
        }  
        }
          if(bolpoz==false){
        if(Pozitie4.isSelected()){
             bolpoz=true;
             String1=" AND Pozitie=Periferie";
        }
        }
        else{
          if(Pozitie4.isSelected()){
             bolpoz=true;
             String1=" OR Pozitie=Periferie";
        }  
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void Pozitie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pozitie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pozitie1ActionPerformed

    private void Confort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confort1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confort1ActionPerformed

    private void Mobila3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mobila3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mobila3ActionPerformed

    private void Bucatarie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bucatarie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bucatarie1ActionPerformed

    private void Bucatarie3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bucatarie3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bucatarie3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void ExclusivitateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExclusivitateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExclusivitateActionPerformed

    private void CuimaginiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuimaginiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuimaginiActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             //POZITIE           
        Boolean bolpoz=false;
        String String1=null;
        if(bolpoz==false){
        if(Pozitie1.isSelected()){
             bolpoz=true;
             String1=" AND Pozitie=Ultracentral";
        }
        }
        else{
          if(Pozitie1.isSelected()){
             bolpoz=true;
             String1=" OR Pozitie=Ultracentral";
        }
        }
        if(bolpoz==false){
        if(Pozitie2.isSelected()){
             bolpoz=true;
             String1=" AND Pozitie=Central";
        }
        }
        else{
          if(Pozitie2.isSelected()){
             bolpoz=true;
             String1=" OR Pozitie=Central";
        }  
        }
         if(bolpoz==false){
        if(Pozitie3.isSelected()){
             bolpoz=true;
             String1=" AND Pozitie=Cartier";
        }
        }
        else{
          if(Pozitie3.isSelected()){
             bolpoz=true;
             String1=" OR Pozitie=Cartier";
        }  
        }
          if(bolpoz==false){
        if(Pozitie4.isSelected()){
             bolpoz=true;
             String1=" AND Pozitie=Periferie";
        }
        }
        else{
          if(Pozitie4.isSelected()){
             bolpoz=true;
             String1=" OR Pozitie=Periferie";
        }  
        }
          
         //DESTINATIE
         
         Boolean boldest=false;
         String String2=null;
        if(boldest==false){
        if(Dest1.isSelected()){
             boldest=true;
             String2=" AND Destinatie=Rezidential";
        }
        }
        else{
          if(Dest1.isSelected()){
             boldest=true;
             String2=" OR Destinatie=Rezidential";
        }
        }
        if(boldest==false){
        if(Dest2.isSelected()){
             boldest=true;
             String2=" AND Destinatie=Comercial";
        }
        }
        else{
          if(Dest2.isSelected()){
             boldest=true;
             String2=" OR Pozitie=Comercial";
        }  
        }
         if(boldest==false){
        if(Dest3.isSelected()){
             boldest=true;
             String2=" AND Destinatie=Birouri";
        }
        }
        else{
          if(Dest3.isSelected()){
             boldest=true;
             String2=" OR Destinatie=Birouri";
        }  
        }
          if(boldest==false){
        if(Dest4.isSelected()){
             boldest=true;
             String2=" AND Destinatie=Vacanta";
        }
        }
        else{
          if(Dest4.isSelected()){
             boldest=true;
             String2=" OR Destinatie=Vacanta";
        }  
        } 
          
         //CAMERE 
          
         Boolean bolcam=false;
         String String3=null;
        if(bolcam==false){
        if(Camera1.isSelected()){
             bolcam=true;
             String3=" AND Camere=1";
        }
        }
        else{
          if(Camera1.isSelected()){
             bolcam=true;
             String3=" OR Camere=1";
        }
        }
        if(bolcam==false){
        if(Camera2.isSelected()){
             bolcam=true;
             String3=" AND Camere=2";
        }
        }
        else{
          if(Camera2.isSelected()){
             bolcam=true;
             String3=" OR Camere=2";
        }  
        }
         if(bolcam==false){
        if(Camera3.isSelected()){
             bolcam=true;
             String3=" AND Camere=3";
        }
        }
        else{
          if(Camera3.isSelected()){
             bolcam=true;
             String3=" OR Camere=3";
        }  
        }
          if(bolcam==false){
        if(Camera4.isSelected()){
             bolcam=true;
             String3=" AND Camere=4";
        }
        }
        else{
          if(Camera4.isSelected()){
             bolcam=true;
             String3=" OR Camere=4";
        }  
        }   
        if(bolcam==false){
        if(Camera5.isSelected()){
             bolcam=true;
             String3=" AND Camere>4";
        }
        }
        else{
          if(Camera5.isSelected()){
             bolcam=true;
             String3=" OR Camere>4";
        }  
        }     
        
        //CONFORT
        
        
        
         Boolean bolconfort=false;
         String String4=null;
        if(bolconfort==false){
        if(Confort1.isSelected()){
             bolconfort=true;
             String4=" AND Confort=I+";
        }
        }
        else{
          if(Confort1.isSelected()){
             bolconfort=true;
             String4=" OR Confort=I+";
        }
        }
        if(bolconfort==false){
        if(Confort2.isSelected()){
             bolconfort=true;
             String4=" AND Confort=I";
        }
        }
        else{
          if(Confort2.isSelected()){
             bolconfort=true;
             String4=" OR Confort=I";
        }  
        }
         if(bolconfort==false){
        if(Confort3.isSelected()){
             bolconfort=true;
             String4=" AND Confort=II+";
        }
        }
        else{
          if(Confort3.isSelected()){
             bolconfort=true;
             String4=" OR Confort=II+";
        }  
        }
          if(bolconfort==false){
        if(Confort4.isSelected()){
             bolconfort=true;
             String4=" AND Confort=II";
        }
        }
        else{
          if(Confort4.isSelected()){
             bolconfort=true;
             String4=" OR Confort=II";
        }  
        }   
        if(bolconfort==false){
        if(Confort5.isSelected()){
             bolconfort=true;
             String4=" AND Confort=III+";
        }
        }
        else{
          if(Confort5.isSelected()){
             bolconfort=true;
             String4=" OR Confort=III+";
        }  
        }     
        if(bolconfort==false){
        if(Confort6.isSelected()){
             bolconfort=true;
             String4=" AND Confort=III";
        }
        }
        else{
          if(Confort6.isSelected()){
             bolconfort=true;
             String4=" OR Confort=III";
        }  
        }     
         
        
        //MOBILA
        
       Boolean bolmob=false;
        String String5=null;
        if(bolmob==false){
        if(Mobila1.isSelected()){
             bolmob=true;
             String5=" AND Mobila=Nemobilat";
        }
        }
        else{
          if(Mobila1.isSelected()){
             bolmob=true;
             String5=" OR Mobila=Nemobilat";
        }
        }
        if(bolmob==false){
        if(Mobila2.isSelected()){
             bolmob=true;
             String5=" AND Mobila=Mobilat partial";
        }
        }
        else{
          if(Mobila2.isSelected()){
             bolmob=true;
             String5=" OR Mobila=Mobilat partial";
        }  
        }
         if(bolmob==false){
        if(Mobila3.isSelected()){
             bolmob=true;
             String5=" AND Mobila=Mobilat complet";
        }
        }
        else{
          if(Mobila3.isSelected()){
             bolmob=true;
             String5=" OR Mobila=Mobilat complet";
        }  
        }
          if(bolmob==false){
        if(Mobila4.isSelected()){
             bolmob=true;
             String5=" AND Mobila=Mobilat lux";
        }
        }
        else{
          if(Mobila4.isSelected()){
             bolmob=true;
             String5=" OR Mobila=Mobilat lux";
        }  
        }
           
          //BUCATARIE
        
         Boolean bolbucat=false;
        String String6=null;
        if(bolbucat==false){
        if(Bucatarie1.isSelected()){
             bolbucat=true;
             String6=" AND Bucatarie=Nemobilata";
        }
        }
        else{
          if(Bucatarie1.isSelected()){
             bolbucat=true;
             String6=" OR Bucatarie=Nemobilata";
        }
        }
        if(bolbucat==false){
        if(Bucatarie2.isSelected()){
             bolbucat=true;
             String6=" AND Bucatarie=Mobilata partial";
        }
        }
        else{
          if(Bucatarie2.isSelected()){
             bolbucat=true;
             String6=" OR Bucatarie=Mobilata partial";
        }  
        }
         if(bolbucat==false){
        if(Bucatarie3.isSelected()){
             bolbucat=true;
             String6=" AND Bucatarie=Mobilata complet";
        }
        }
        else{
          if(Bucatarie3.isSelected()){
             bolbucat=true;
             String6=" OR Bucatarie=Mobilata complet";
        }  
        } 
         
        //TIP 
        
        Boolean boltip=false;
        String String7=null;
        if(boltip==false){
        if(Tip1.isSelected()){
             boltip=true;
             String7=" AND Tip=Semidecomandat";
        }
        }
        else{
          if(Tip1.isSelected()){
             boltip=true;
             String7=" OR Tip=Semidecomandat";
        }
        }
        if(boltip==false){
        if(Tip2.isSelected()){
             boltip=true;
             String7=" AND Tip=Decomandat";
        }
        }
        else{
          if(Tip2.isSelected()){
             boltip=true;
             String7=" OR Tip=Decomandat";
        }  
        }
         if(boltip==false){
        if(Tip3.isSelected()){
             boltip=true;
             String7=" AND Tip=Circular";
        }
        }
        else{
          if(Tip3.isSelected()){
             boltip=true;
             String7=" OR Tip=Circular";
        }  
        }  
         
         //STARE
        
          Boolean bolstare=false;
        String String8=null;
        if(bolstare==false){
        if(Stare1.isSelected()){
             bolstare=true;
             String8=" AND Stare=Actual";
        }
        }
        else{
          if(Stare1.isSelected()){
             bolstare=true;
             String8=" OR Stare=Actual";
        }
        }
        if(bolstare==false){
        if(Stare2.isSelected()){
             bolstare=true;
             String8=" AND Stare=Incorect";
        }
        }
        else{
          if(Stare2.isSelected()){
             bolstare=true;
             String8=" OR Stare=Incorect";
        }  
        }
         if(bolstare==false){
        if(Stare3.isSelected()){
             bolstare=true;
             String8=" AND Stare=Vandut";
        }
        }
        else{
          if(Stare3.isSelected()){
             bolstare=true;
             String8=" OR Stare=Vandut";
        }  
        } 
          
          
          
          
          
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apt_Vanzare_meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apt_Vanzare_meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apt_Vanzare_meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apt_Vanzare_meniu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apt_Vanzare_meniu().setVisible(true);
            }
        });
    }
 //TableIcon table=new TableIcon();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Bucatarie1;
    private javax.swing.JCheckBox Bucatarie2;
    private javax.swing.JCheckBox Bucatarie3;
    private javax.swing.JCheckBox Camera1;
    private javax.swing.JCheckBox Camera2;
    private javax.swing.JCheckBox Camera3;
    private javax.swing.JCheckBox Camera4;
    private javax.swing.JCheckBox Camera5;
    private javax.swing.JCheckBox Clientifavoriti;
    private javax.swing.JCheckBox Confort1;
    private javax.swing.JCheckBox Confort2;
    private javax.swing.JCheckBox Confort3;
    private javax.swing.JCheckBox Confort4;
    private javax.swing.JCheckBox Confort5;
    private javax.swing.JCheckBox Confort6;
    private javax.swing.JCheckBox Cuimagini;
    private javax.swing.JCheckBox Dest1;
    private javax.swing.JCheckBox Dest2;
    private javax.swing.JCheckBox Dest3;
    private javax.swing.JCheckBox Dest4;
    private javax.swing.JComboBox<String> EUR;
    private javax.swing.JCheckBox Exclusivitate;
    private javax.swing.JCheckBox Faraimagini;
    private javax.swing.JCheckBox Metrou;
    private javax.swing.JCheckBox Mobila1;
    private javax.swing.JCheckBox Mobila2;
    private javax.swing.JCheckBox Mobila3;
    private javax.swing.JCheckBox Mobila4;
    private javax.swing.JCheckBox Pozitie1;
    private javax.swing.JCheckBox Pozitie2;
    private javax.swing.JCheckBox Pozitie3;
    private javax.swing.JCheckBox Pozitie4;
    private javax.swing.JCheckBox Publicate;
    private javax.swing.JCheckBox Stare1;
    private javax.swing.JCheckBox Stare2;
    private javax.swing.JCheckBox Stare3;
    private javax.swing.JCheckBox Tip1;
    private javax.swing.JCheckBox Tip2;
    private javax.swing.JCheckBox Tip3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
