/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import com.mysql.jdbc.Driver;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.OutputStreamWriter;
import javax.swing.JOptionPane;
/**
 *
 * @author Razvan
 */

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * 
     */
    public static String User;
    public static int UserId;
    
    public Login() {
        initComponents();
        try{
        String userName="";
        String password="";
        if(tempFile.exists()){//This is subsequent login 
            
            System.out.println("ramura1");
            
            String line;
            BufferedReader reader = new BufferedReader(new FileReader (tempFile));
            
            while((line = reader.readLine()) != null) {
                System.out.println("usr "+userName);
                if(userName.equalsIgnoreCase("")){
                    userName = line;
                    System.out.println("usr "+userName);
                }else{
                    password = line;
                    System.out.println("usr "+password);
                }
        }
            
            LoginTextField.setText(userName);
            PasswordField.setText(password);
            
            
            //Write your code to read file and 
            //your application logic
        }else{ //This is first login 
            tempFile.createNewFile();
            //Write your logic to write data to the file 
            
            System.out.println("ramura2");
        }
        }catch(Exception e){
            e.printStackTrace();
        }
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginTextField.setText("Username");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PasswordField)
                    .addComponent(LoginTextField)
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(LoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginButton)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        
        
        
        
        Statement stmt = null;
                try {
                    
        
        //DriverManager.registerDriver(new com.mysql.jdbc.Driver());
        Class.forName("com.mysql.jdbc.Driver");

       Connection conn = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/imobiliare", "razvan", "razvan");
        
        stmt = (Statement) conn.createStatement();

        ResultSet rs1;
       rs1 = stmt.executeQuery("select * from users");
       Boolean flagLogin=false;
       
        
        while(rs1.next()){
            
            
        
        
            
            String f=new String(PasswordField.getPassword());
            if((LoginTextField.getText().equals(rs1.getString("UserName")))&&(f.equals(rs1.getString("Password")))){
                
                flagLogin=true;
                User=rs1.getString("UserName");
                UserId=rs1.getInt("ID");
                break;

            }
            
              
            }
            if(flagLogin==false){
                JOptionPane.showMessageDialog(Login.this,"Login Failed","Error Message",JOptionPane.ERROR_MESSAGE);
            }
            if(flagLogin==true){
                    MeniuInserare m=new MeniuInserare();
                    
                    this.setVisible(false);
                    m.setVisible(true);
                    FileOutputStream fos = new FileOutputStream(tempFile);
 
                    BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fos));
                    bw.write(LoginTextField.getText());
                    bw.newLine();
                    bw.write(new String(PasswordField.getPassword()));
                    bw.newLine();
                    bw.close();
                }
        
                }
                catch(Exception e){
                    e.printStackTrace();
                }
                
    }//GEN-LAST:event_LoginButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }
    private Login l;
    String tempDir = System.getProperty("java.io.tmpdir");
    File tempFile = new File(new File(tempDir), "userDetail.tmp");
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField LoginTextField;
    private javax.swing.JPasswordField PasswordField;
    // End of variables declaration//GEN-END:variables
}

